services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  redis:
    image: redis:7.2-alpine
    container_name: redis-local-secure
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - ./configs/certs:/certs:ro
      - ./configs/users.acl:/etc/redis/users.acl:ro
    command: >
      redis-server 
      --tls-port 6380
      --port 0 
      --tls-cert-file /certs/redis.crt 
      --tls-key-file /certs/redis.key 
      --tls-ca-cert-file /certs/redis.crt 
      --tls-auth-clients no 
      --aclfile /etc/redis/users.acl 
      --appendonly yes
