services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - auth-server
  auth-server:
    build:
      context: .
      dockerfile: apps/auth-server/Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
  shortlid-server:
    build:
      context: .
      dockerfile: apps/shortlid-server/Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  shortlid-web:
    build:
      context: .
      dockerfile: apps/shortlid-web/Dockerfile
      args:
        - SERVER=http://localhost:3333
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - shortlid-server
  redis:
    image: redis:7.2-alpine
    container_name: redis-local-secure
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - ./configs/certs:/certs:ro
      - ./configs/users.acl:/etc/redis/users.acl:ro
    command: >
      redis-server 
      --tls-port 6380
      --port 0 
      --tls-cert-file /certs/redis.crt 
      --tls-key-file /certs/redis.key 
      --tls-ca-cert-file /certs/redis.crt 
      --tls-auth-clients no 
      --aclfile /etc/redis/users.acl 
      --appendonly yes

networks:
  default:
    driver: bridge
