FROM node:22-alpine AS build

WORKDIR /app

COPY apps/server/package.json package-lock.json ./
RUN npm install

COPY ./apps/server .
RUN npm run generate:dev && npm run build

FROM node:22-alpine AS production

WORKDIR /app

COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

EXPOSE 8080

CMD ["npm", "run", "start"]